apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: go-web-server-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: image
      type: image
  tasks:
    - name: build-go-web-server
      taskRef:
        name: build-docker-image-from-git-source
      params:
        - name: pathToDockerfile
          value: Dockerfile
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: image
    - name: deploy-go-web-server
      taskRef:
        name: deploy-using-kubectl
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: image
            from:
              - build-go-web-server
      params:
        - name: path
          value: /workspace/source/k8s.yaml
        - name: yamlPathToImage
          value: ".spec.template.spec.containers[0].image"